name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run build.bat
        shell: cmd
        run: build.bat

      - name: Run installer build.bat
        shell: cmd
        run: installer/build.bat

      - name: Extract version
        id: get_version
        shell: bash
        run: |
          VERSION=$(grep 'Number = "' version/version.go | sed 's/.*Number = "\(.*\)"/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in installer/dist/*; do
            gh release upload v${{ steps.get_version.outputs.VERSION }} "$file" --repo ${{ github.repository }}
          done
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            x86/**
            amd64/**
            arm64/**
            installer/dist/**
